language: node_js
node_js:
  - 14.0.0

services:
  - docker

script:
  - docker --version # smoke test
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy abukavictor/reverseproxy:v1
  - docker tag udagram-frontend abukavictor/udagram-frontend:v1
  - docker tag udagram-api-feed abukavictor/udagram-api-feed:v1
  - docker tag udagram-api-user abukavictor/udagram-api-user:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push abukavictor/reverseproxy:v1
  - docker push abukavictor/udagram-frontend:v1
  - docker push abukavictor/udagram-api-feed:v1
  - docker push abukavictor/udagram-api-user:v1